import type { Metadata } from "next";
import { Alata,Rethink_Sans } from "next/font/google";
import "./globals.css";

const alataSans = Alata({
  variable: "--font-alata",
  subsets: ['latin'],
  weight: '400'
})

const rethinkSans = Rethink_Sans({
  variable: "--font-rethink",
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alataSans.variable} ${rethinkSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
